--- #YAML:1.0
name: Module-CPANTS-Generator
version: 0.011
license: perl
distribution_type: module
requires:
  AppConfig: 0
  CPAN::DistnameInfo: 0.04
  CPANPLUS: 0.042
  Test::More: 0.01
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Module::CPANTS::Generator:
    file: lib/Module/CPANTS/Generator.pm
    version: 0.011
  Module::CPANTS::Generator::Files:
    file: lib/Module/CPANTS/Generator/Files.pm
    version: 0.011
  Module::CPANTS::Generator::Init:
    file: lib/Module/CPANTS/Generator/Init.pm
    version: 0.011
  Module::CPANTS::Generator::Prereq:
    file: lib/Module/CPANTS/Generator/Prereq.pm
    version: 0.011
  Module::CPANTS::Metrics:
    file: lib/Module/CPANTS/Metrics.pm
    version: 0.011
  Module::CPANTS::Reporter:
    file: lib/Module/CPANTS/Reporter.pm
    version: 0.011
  Module::CPANTS::Reporter::DB:
    file: lib/Module/CPANTS/Reporter/DB.pm
    version: 0.011
  Module::CPANTS::Reporter::DataDumper:
    file: lib/Module/CPANTS/Reporter/DataDumper.pm
    version: 0.011
  Module::CPANTS::Reporter::STDOUT:
    file: lib/Module/CPANTS/Reporter/STDOUT.pm
    version: 0.011
  Module::CPANTS::Reporter::asHash:
    file: lib/Module/CPANTS/Reporter/asHash.pm
    version: 0.011
  Module::CPANTS::Reporter::asSQLite:
    file: lib/Module/CPANTS/Reporter/asSQLite.pm
    version: 0.011
  Module::CPANTS::asHash:
    file: lib/Module/CPANTS/Reporter/asHash.pm
    version: 0.011
  varchar:
    file: lib/Module/CPANTS/Generator/Init.pm
    version: 0.011
generated_by: Module::Build version 0.21
