--- #YAML:1.0
name: Module-CPANTS-Generator
version: 0.23
author:
  - Thomas Klausner <domm@zsi.at> http://domm.zsi.at
  - |-
    Please use the perl-qa mailing list for discussing all things CPANTS:
    http://lists.perl.org/showlist.cgi?name=perl-qa
  - |-
    based on work by Leon Brocard <acme@astray.com> and the original idea
    proposed by Michael G. Schwern <schwern@pobox.com>
abstract: Generate CPANTS statistics
license: perl
requires:
  AppConfig: 1.56
  CPAN::DistnameInfo: 0.05
  CPANPLUS: 0.049
  Class::Accessor: 0.19
  Class::Data::Inheritable: 0.02
  DBD::SQLite: 0.31
  DBI: 1.42
  DateTime: 0.21
  Module::MakefilePL::Parse: 0.11
  Pod::Simple::Checker: 2.02
  Storable: 2.09
  Term::ProgressBar: 1.18
  Test::More: 0.01
  YAML: 0.35
provides:
  Module::CPANTS::Generator:
    file: lib/Module/CPANTS/Generator.pm
    version: 0.23
  Module::CPANTS::Generator::CPAN:
    file: lib/Module/CPANTS/Generator/CPAN.pm
    version: 0.23
  Module::CPANTS::Generator::Files:
    file: lib/Module/CPANTS/Generator/Files.pm
    version: 0.23
  Module::CPANTS::Generator::Pod:
    file: lib/Module/CPANTS/Generator/Pod.pm
    version: 0.23
  Module::CPANTS::Generator::Prereq:
    file: lib/Module/CPANTS/Generator/Prereq.pm
    version: 0.23
  Module::CPANTS::Generator::Unpack:
    file: lib/Module/CPANTS/Generator/Unpack.pm
    version: 0.23
  text:
    file: lib/Module/CPANTS/Generator/Unpack.pm
    version: 0.23
generated_by: Module::Build version 0.25
