---
name: Module-CPANTS-Generator
version: 0.40
author:
  - Thomas Klausner <domm@zsi.at> http://domm.zsi.at
  - |-
    based on work by Leon Brocard <acme@astray.com> and the original idea
    proposed by Michael G. Schwern <schwern@pobox.com>
abstract: Generate CPANTS statistics
license: perl
requires:
  Archive::Any: 0.06
  CPAN::DistnameInfo: 0.05
  CPANPLUS: 0.053
  Class::Accessor: 0.19
  Class::DBI: 0.96
  Class::DBI::Pager: 0.05
  DBD::SQLite: 0.31
  DBI: 1.42
  IO::Capture: 0.03
  Module::ExtractUse: 0.15
  Module::Pluggable: 2.8
  Parse::CPAN::Packages: 2.24
  Pod::Simple: 3.02
  YAML: 0.36
provides:
  Module::CPANTS::Config:
    file: lib/Module/CPANTS/Config.pm
  Module::CPANTS::DB:
    file: lib/Module/CPANTS/DB.pm
  Module::CPANTS::DB::Author:
    file: lib/Module/CPANTS/DB.pm
  Module::CPANTS::DB::Dist:
    file: lib/Module/CPANTS/DB.pm
  Module::CPANTS::DB::Kwalitee:
    file: lib/Module/CPANTS/DB.pm
  Module::CPANTS::DB::Modules:
    file: lib/Module/CPANTS/DB.pm
  Module::CPANTS::DB::Prereq:
    file: lib/Module/CPANTS/DB.pm
  Module::CPANTS::DB::Uses:
    file: lib/Module/CPANTS/DB.pm
  Module::CPANTS::Generator:
    file: lib/Module/CPANTS/Generator.pm
    version: 0.40
  Module::CPANTS::Generator::Authors:
    file: lib/Module/CPANTS/Generator/Authors.pm
  Module::CPANTS::Generator::Files:
    file: lib/Module/CPANTS/Generator/Files.pm
  Module::CPANTS::Generator::FindModules:
    file: lib/Module/CPANTS/Generator/FindModules.pm
  Module::CPANTS::Generator::Pod:
    file: lib/Module/CPANTS/Generator/Pod.pm
  Module::CPANTS::Generator::Prereq:
    file: lib/Module/CPANTS/Generator/Prereq.pm
  Module::CPANTS::Generator::Unpack:
    file: lib/Module/CPANTS/Generator/Unpack.pm
  Module::CPANTS::Generator::Uses:
    file: lib/Module/CPANTS/Generator/Uses.pm
generated_by: Module::Build version 0.2609
