---
name: Module-CPANTS-Generator
version: 0.30
author:
  - Thomas Klausner <domm@zsi.at> http://domm.zsi.at
  - |-
    based on work by Leon Brocard <acme@astray.com> and the original idea
    proposed by Michael G. Schwern <schwern@pobox.com>
abstract: Generate CPANTS statistics
license: perl
requires:
  AppConfig: 1.56
  CPAN::DistnameInfo: 0.05
  CPANPLUS: 0.053
  Class::Accessor: 0.19
  Class::Data::Inheritable: 0.02
  DBD::SQLite: 0.31
  DBI: 1.42
  DateTime: 0.21
  Module::ExtractUse: 0.15
  Pod::Simple::Checker: 2.02
  Pod::Strip: 1.00
  Storable: 2.09
  Term::ProgressBar: 1.18
  Test::More: 0.01
  YAML: 0.35
provides:
  Module::CPANTS::Generator:
    file: lib/Module/CPANTS/Generator.pm
    version: 0.30
  Module::CPANTS::Generator::CPAN:
    file: lib/Module/CPANTS/Generator/CPAN.pm
  Module::CPANTS::Generator::Files:
    file: lib/Module/CPANTS/Generator/Files.pm
  Module::CPANTS::Generator::FindModules:
    file: lib/Module/CPANTS/Generator/FindModules.pm
  Module::CPANTS::Generator::Pod:
    file: lib/Module/CPANTS/Generator/Pod.pm
  Module::CPANTS::Generator::Prereq:
    file: lib/Module/CPANTS/Generator/Prereq.pm
  Module::CPANTS::Generator::Unpack:
    file: lib/Module/CPANTS/Generator/Unpack.pm
  Module::CPANTS::Generator::Uses:
    file: lib/Module/CPANTS/Generator/Uses.pm
  text:
    file: lib/Module/CPANTS/Generator/Unpack.pm
generated_by: Module::Build version 0.2609
