--- #YAML:1.0
name: Module-CPANTS-Generator
version: 0.010
license: perl
distribution_type: module
requires:
  AppConfig: 0
  CPAN::DistnameInfo: 0.04
  CPANPLUS: 0.042
  Test::More: 0.01
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Module::CPANTS::Generator:
    file: lib/Module/CPANTS/Generator.pm
    version: 0.010
  Module::CPANTS::Generator::Files:
    file: lib/Module/CPANTS/Generator/Files.pm
  Module::CPANTS::Generator::Init:
    file: lib/Module/CPANTS/Generator/Init.pm
  Module::CPANTS::Generator::Prereq:
    file: lib/Module/CPANTS/Generator/Prereq.pm
  Module::CPANTS::Metrics:
    file: lib/Module/CPANTS/Metrics.pm
  Module::CPANTS::Reporter:
    file: lib/Module/CPANTS/Reporter.pm
  Module::CPANTS::Reporter::DB:
    file: lib/Module/CPANTS/Reporter/DB.pm
  Module::CPANTS::Reporter::DataDumper:
    file: lib/Module/CPANTS/Reporter/DataDumper.pm
  Module::CPANTS::Reporter::asHash:
    file: lib/Module/CPANTS/Reporter/asHash.pm
    version: '%version%'
  Module::CPANTS::Reporter::asSQLite:
    file: lib/Module/CPANTS/Reporter/asSQLite.pm
  Module::CPANTS::asHash:
    file: lib/Module/CPANTS/Reporter/asHash.pm
    version: '%version%'
  varchar:
    file: lib/Module/CPANTS/Generator/Init.pm
generated_by: Module::Build version 0.21
